name: hyprbm-torch-netket
dependencies:
  - python=3.11
  - pip
  - pip:
      - notebook==7.5.3
      - matplotlib==3.10.8
      - scienceplots==2.2.0
      - numpy==2.3.5
      - pandas==3.0.0
      - torch==2.10.0
      - tqdm==4.67.3